language: r
warnings_are_errors: false
sudo: required

r_binary_packages:
  - rgdal
  - rgeos

r_packages:
  - covr
  - sp
  - dygraphs
  - xts
  - RCurl
  - xts,
  - leaflet,
  - mapview,
  - htmlwidgets,
  - DT
  
after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
