language: r
warnings_are_errors: false
sudo: required

r_binary_packages:
  - rgdal
  - rgeos

r_packages:
  - covr
  - sp
  - RCurl
  
after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
