language: r
warnings_are_errors: false
sudo: required

before_install:
  - sudo apt-get -y install aptitude
  - sudo aptitude -y install libgdal-dev
  - sudo aptitude -y install libproj-dev

r_packages:
  - covr
  - sp
  - rgdal
  - rgeos
  
after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
