language: r
r:
  - 3.3.1

warnings_are_errors: false
sudo: required

r_binary_packages:
  - rgdal
  - rgeos

r_packages:
  - covr
<<<<<<< HEAD
  - sp
  - RCurl
  - xtable
  - DT
  - htmlwidgets
  - leaflet
  - mapview

=======
  
>>>>>>> 38a6db11a31be504d442785a681579ce451d848d
after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
