language: r
warnings_are_errors: false
sudo: required

before_install:
  - sudo apt-get install libhdf5-7 libhdf5-dev libhdf5-serial-dev libgdal1h libnetcdf-dev libgdal-dev libhdf4-alt-dev libproj-dev
r_packages:
  - covr

after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change