language: r
warnings_are_errors: false
sudo: required

before_install:
  - sudo apt-get -y install libgdal1-dev libgdal-dev libgeos-c1=3.3.3-1.1 libspatialite3=3.1.0~rc2-1ubuntu1

r_packages:
  - covr

after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change